active_modules:
  iso15118_charger:
    module: EvseV2G
    config_module:
      device: auto
      tls_security: allow
      verify_contract_cert_chain: false
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
  iso15118_car:
    module: PyEvJosev
    config_module:
      device: auto
      supported_ISO15118_2: true
      tls_active: true
      is_cert_install_needed: true
  evse_manager:
    module: EvseManager
    mapping:
      module:
        evse: 1
    config_module:
      connector_id: 1
      evse_id: "DE*PNX*SIM0001"
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp/everest-logs
      ac_hlc_enabled: true
      ac_hlc_use_5percent: false
      ac_enforce_hlc: false
    connections:
      bsp:
        - module_id: yeti_driver
          implementation_id: board_support
      powermeter_grid_side:
        - module_id: yeti_driver
          implementation_id: powermeter
      slac:
        - module_id: slac
          implementation_id: evse
      hlc:
        - module_id: iso15118_charger
          implementation_id: charger
  yeti_driver:
    module: YetiSimulator
    config_module:
      connector_id: 1
  slac:
    module: SlacSimulator
  ev_manager:
    module: EvManager
    config_module:
      connector_id: 1
      auto_enable: true
      auto_exec: true
      auto_exec_commands: sleep 1;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 30;unplug
    connections:
      ev_board_support:
        - module_id: yeti_driver
          implementation_id: ev_board_support
      ev:
        - module_id: iso15118_car
          implementation_id: ev
      slac:
        - module_id: slac
          implementation_id: ev
  evse_security:
    module: EvseSecurity
    config_module:
      private_key_password: "123456"
  token_provider:
    module: DummyTokenProviderManual
    config_implementation:
      main:
        token: DEMO_TOKEN
        type: PnC
        timeout: 60
  token_validator:
    module: DummyTokenValidator
    config_implementation:
      main:
        validation_result: Accepted
        validation_reason: Token valid for demo
        sleep: 0.25
  auth:
    module: Auth
    config_module:
      connection_timeout: 120
      selection_algorithm: PlugEvents
    connections:
      token_provider:
        - module_id: token_provider
          implementation_id: main
      token_validator:
        - module_id: token_validator
          implementation_id: main
      evse_manager:
        - module_id: evse_manager
          implementation_id: evse
  evse_manager_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 1
    config_module:
      fuse_limit_A: 32.0
      phase_count: 3
    connections:
      energy_consumer:
        - module_id: evse_manager
          implementation_id: energy_grid
      powermeter:
        - module_id: yeti_driver
          implementation_id: powermeter
  grid_connection_point:
    module: EnergyNode
    mapping:
      module:
        evse: 0
    config_module:
      fuse_limit_A: 40.0
      phase_count: 3
    connections:
      energy_consumer:
        - module_id: evse_manager_sink
          implementation_id: energy_grid
  energy_manager:
    module: EnergyManager
    connections:
      energy_trunk:
        - module_id: grid_connection_point
          implementation_id: energy_grid
  system:
    module: System

x-module-layout: {}
